url: http://polygon-js.github.io
baseurl: /

title: Polygon | Modern JS Library
description:  A Modern JavaScript Library

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: docs
    values:
      layour: docs
